### ISSUE TITLE
Add Nanokontrol2 and Studio support

### ISSUE THREAD

**Issue by ho0ber** [ho0ber/havomi#9]
I need to actually go find my nk2 for this, ideally. Once the basic nk2 is done, then port the config to the sudio using the draft from discord

**Comment by ho0ber** [comment]
blocked on not being able to find my nk2 and on not having an nk-studio. I've made a first attempt for the nk-studio:
https://github.com/ho0ber/havomi/commit/ef236ecb91f5ae3e26f65b8fa17573b2cf564770

**Comment by ho0ber** [comment]
Found my nk2 - up and running.

Calling this done because I can't test any further because I don't have a studio.

https://github.com/ho0ber/havomi/commit/3fcce25f257196b85f6a65ba0f05a2cf2de14b0f

**Comment by ketvos** [comment]
NK-Studio notes: Reset to factory by holding down the Scene, and Stop buttons, turn the nanoKONTROL Studio on. If you set the LEDs to external using the software (just like NK2) they also work. Since the studio doesn't have a big 'next track' button I've assigned the record button to use this media feature instead of using a smaller button.
[nk-studio config.zip](https://github.com/ho0ber/havomi/files/7833397/nk-studio.config.zip)
